name: build and scan
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Update to the latest Node.js 20 version
      - name: Install dependencies
        run: npm clean-install

